/* MS SQL */
SELECT C.NAME, O.PRICE
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.ORDER_ID = O.ID
WHERE
O.PRICE = (SELECT MAX(PRICE) FROM ORDERS WHERE ORDER_DATE <= DATEADD(year, 10, (SELECT MIN(ORDER_DATE) FROM ORDERS))) AND
O.ORDER_DATE <= DATEADD(year, 10, (SELECT MIN(ORDER_DATE) FROM ORDERS))

/* Oracle SQL */
SELECT C.NAME, O.PRICE
FROM CUSTOMERS C INNER JOIN ORDERS O ON C.ORDER_ID = O.ID
WHERE
O.PRICE = (SELECT MAX(PRICE) FROM ORDERS WHERE ORDER_DATE <= ADD_MONTHS((SELECT MIN(ORDER_DATE) FROM ORDERS), 120)) AND
O.ORDER_DATE <= ADD_MONTHS((SELECT MIN(ORDER_DATE) FROM ORDERS), 120)
