/* MS SQL */
SELECT GENDER, BG, SUM(TOTAL)
FROM
(SELECT GENDER, BG, COUNT(BG) TOTAL
FROM DONOR
GROUP BY GENDER, BG
UNION ALL
SELECT GENDER, BG, COUNT(BG) TOTAL
FROM ACCEPTOR
GROUP BY GENDER, BG) A
GROUP BY GENDER, BG
ORDER BY GENDER, BG;